name: tf1
channels:
  - conda-forge
  - defaults
dependencies:
  - atari_py=0.2 # used only in chapter 16
  - box2d-py=2.3 # used only in chapter 16
  - graphviz # used only in chapter 6 for dot files
  - gym=0.18 # used only in chapter 16
  - ipython=7.20 # a powerful Python shell
  - joblib=0.14 # used only in chapter 2 to save/load Scikit-Learn models
  - jupyter=1.0 # to edit and run Jupyter notebooks
  - matplotlib=3.3 # beautiful plots. See tutorial tools_matplotlib.ipynb
  - nbdime=2.1 # optional tool to diff Jupyter notebooks
  - nltk=3.4 # optionally used in chapter 3, exercise 4
  - numexpr=2.7 # used only in the Pandas tutorial for numerical expressions
  - numpy=1.19 # Powerful n-dimensional arrays and numerical computing tools
  - pandas=1.2 # data analysis and manipulation tool
  - pillow=8.1 # image manipulation library, (used by matplotlib.image.imread)
  - pip # Python's package-management system
  - py-xgboost=0.90 # used only in chapter 7 for optimized Gradient Boosting
  - pyglet=1.5 # used only in chapter 16 to render environments
  - pyopengl=3.1 # used only in chapter 16 to render environments
  - python=3.7 # Python! Not using latest version as some libs lack support
  - python-graphviz # used only in chapter 6 for dot files
 #- pyvirtualdisplay=1.3 # used only in chapter 16 if on headless server
  - scikit-image=0.18.1 # used only in chapter 13 to resize images
  - scikit-learn=0.24 # machine learning library
  - scipy=1.6 # scientific/technical computing library
  - transformers=4.3 # Natural Language Processing lib for TF or PyTorch
  - wheel # built-package format for pip
  - widgetsnbextension=3.5 # interactive HTML widgets for Jupyter notebooks
  - pip:
    - tensorboard==1.15.0 # TensorFlow's visualization toolkit
    - tensorflow==1.15.5 # or tensorflow-gpu if you have a TF-compatible GPU
    - urlextract==1.2.0 # optionally used in chapter 3, exercise 4
